use axum::async_trait;
use axum::extract::FromRef;
use axum::extract::FromRequestParts;
use axum::http::request::Parts;
use jsonwebtoken::{decode, DecodingKey, Validation};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use common::errors::AppError;

/// JWT claims matching the format generated by the users crate
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Claims {
    pub sub: Uuid,
    pub role: String,
    pub exp: i64,
    pub iat: i64,
}

/// Authenticated user extracted from a valid JWT token
/// This is the chat crate's own extractor (mirrors api::auth_extractor::AuthUser)
/// to avoid circular dependencies (api depends on chat, chat cannot depend on api)
#[derive(Debug, Clone)]
pub struct ChatUser {
    pub id: Uuid,
    pub role: String,
}

#[async_trait]
impl<S> FromRequestParts<S> for ChatUser
where
    S: Send + Sync,
    String: FromRef<S>,
{
    type Rejection = AppError;

    async fn from_request_parts(parts: &mut Parts, state: &S) -> Result<Self, Self::Rejection> {
        let auth_header = parts
            .headers
            .get(axum::http::header::AUTHORIZATION)
            .and_then(|value| value.to_str().ok())
            .ok_or_else(|| AppError::Unauthorized("Cabecera Authorization no encontrada".to_string()))?;

        if !auth_header.starts_with("Bearer ") {
            return Err(AppError::Unauthorized(
                "El token debe usar el formato Bearer".to_string(),
            ));
        }

        let token = &auth_header[7..];
        let jwt_secret = String::from_ref(state);

        let token_data = decode::<Claims>(
            token,
            &DecodingKey::from_secret(jwt_secret.as_bytes()),
            &Validation::default(),
        )
        .map_err(|err| {
            if let jsonwebtoken::errors::ErrorKind::ExpiredSignature = err.kind() {
                AppError::Unauthorized("El token de sesión ha expirado".to_string())
            } else {
                AppError::Unauthorized("Token de sesión inválido".to_string())
            }
        })?;

        Ok(ChatUser {
            id: token_data.claims.sub,
            role: token_data.claims.role,
        })
    }
}
